#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /config/{cache,data,log,packages,plugins,sessions}

symlink -l /app/www/var /config

if [[ -n "${DATABASE_URL}" ]]; then
    cd /app/www || exit 1
    s6-setuidgid abc bin/console kimai:install -n
    s6-setuidgid abc bin/console kimai:update -n
else
    echo "DATABASE_URL not set"
    sleep infinity
fi

lsiown -R abc:abc \
    /config
