#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Echo init finish for test runs
if [ -n "${TEST_RUN}" ]; then
    echo '[ls.io-init] done.'
fi

DB_VALID=$(php -r 'echo filter_var(getenv("DATABASE_URL"), FILTER_VALIDATE_URL, FILTER_FLAG_PATH_REQUIRED);')

if [[ ${DATABASE_URL+x} == "" ]] || [[ ${DB_VALID+x} == "NULL" ]]; then
    cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *     DATABASE_URL environment variable is not set     *
    *                          OR                          *
    *    DATABASE_URL environment variable is not valid    *
    *                                                      *
    *              Please refer to the README              *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
    sleep infinity
fi

# make our folders
mkdir -p \
    /config/www/var/{cache,data,log,packages,plugins,sessions}

rm -rf /app/www/var
ln -s /config/www/var /app/www/var

DB_HOST=$(php -r 'echo parse_url(getenv("DATABASE_URL"), PHP_URL_HOST);')
DB_PORT=$(php -r 'echo parse_url(getenv("DATABASE_URL"), PHP_URL_PORT) ?? 3306;')

# check for the mysql endpoint
echo "Waiting for DB to be available"
END=$((SECONDS + 30))
while [[ ${SECONDS} -lt ${END} ]]; do
    if [[ $(/usr/bin/nc -w1 "${DB_HOST}" "${DB_PORT}" | tr -d '\0') ]]; then
        if [[ -n "${RUN}" ]]; then
            break
        fi
        RUN="RAN"
        # we sleep here again due to first run init on DB containers
        if [[ ! -f /dbwait.lock ]]; then
            sleep 5
        fi
    else
        sleep 1
    fi
done
# set lockfile to avoid DB waits for this specific container
touch /dbwait.lock

lsiown -R abc:abc \
    /config/www

console kimai:install -n
console kimai:update -n
